document.addEventListener('DOMContentLoaded',()=>{
  const $=s=>document.querySelector(s),params=new URLSearchParams(location.search),guest=(params.get('to')||'Tamu Undangan').slice(0,60);$('#guest-name').textContent=guest;
  const initSlider=box=>{const originals=[...box.querySelectorAll(':scope > .slide')];if(originals.length<2)return;const track=document.createElement('div');track.className='continuous-track';originals.forEach(slide=>{slide.classList.remove('active');track.append(slide)});originals.forEach(slide=>{const clone=slide.cloneNode(true);clone.setAttribute('aria-hidden','true');track.append(clone)});box.prepend(track);box.querySelectorAll(':scope > .slider-prev,:scope > .slider-next,:scope > .slider-dots').forEach(control=>control.hidden=true);const sync=()=>{const width=box.clientWidth;if(!width)return;box.style.setProperty('--slide-width',`${width}px`);box.style.setProperty('--loop-distance',`${width*originals.length}px`);box.style.setProperty('--loop-duration',`${Math.max(14,originals.length*6)}s`)};let dragging=false,startX=0,startY=0,baseX=0,dragX=0,moved=false;const translateX=()=>{const matrix=getComputedStyle(track).transform;if(!matrix||matrix==='none')return 0;return new DOMMatrixReadOnly(matrix).m41},wrap=value=>{const distance=box.clientWidth*originals.length;if(!distance)return 0;while(value>0)value-=distance;while(value<=-distance)value+=distance;return value},resume=()=>{const distance=box.clientWidth*originals.length,duration=Math.max(14,originals.length*6),progress=distance?Math.abs(wrap(dragX))/distance:0;track.style.transform='';track.style.animation='none';void track.offsetWidth;track.style.animation=`continuousCarousel ${duration}s linear infinite`;track.style.animationDelay=`-${progress*duration}s`};box.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&event.button!==0)return;dragging=true;moved=false;startX=event.clientX;startY=event.clientY;baseX=translateX();dragX=baseX;track.style.animation='none';track.style.transform=`translate3d(${baseX}px,0,0)`;box.classList.add('is-dragging');box.setPointerCapture?.(event.pointerId)});box.addEventListener('pointermove',event=>{if(!dragging)return;const dx=event.clientX-startX,dy=event.clientY-startY;if(Math.abs(dx)>6)moved=true;if(Math.abs(dy)>Math.abs(dx)&&!moved)return;dragX=wrap(baseX+dx);track.style.transform=`translate3d(${dragX}px,0,0)`});const release=event=>{if(!dragging)return;dragging=false;box.classList.remove('is-dragging');box.releasePointerCapture?.(event.pointerId);resume()};box.addEventListener('pointerup',release);box.addEventListener('pointercancel',release);box.addEventListener('dragstart',event=>event.preventDefault());sync();new ResizeObserver(sync).observe(box)};document.querySelectorAll('.auto-slider').forEach(initSlider);
  const openInvitation=()=>{$('#cover').classList.add('opened');document.body.classList.remove('locked');$('#invitation').setAttribute('aria-hidden','false');playMusic()};$('#open-invitation').onclick=openInvitation;if(params.get('preview')==='1')openInvitation();
  const target=new Date('2026-11-07T09:00:00+07:00').getTime(),tick=()=>{const d=Math.max(0,target-Date.now()),v={days:Math.floor(d/86400000),hours:Math.floor(d/3600000%24),minutes:Math.floor(d/60000%60),seconds:Math.floor(d/1000%60)};Object.entries(v).forEach(([k,x])=>document.getElementById(k).textContent=String(x).padStart(2,'0'))};tick();setInterval(tick,1000);
  const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
  const cal=new URLSearchParams({action:'TEMPLATE',text:'Pernikahan Lizwan & Naomi',dates:'20261107T020000Z/20261107T090000Z',location:'Gereja HKI dan BPU Bagas Raya, Lubuklinggau',details:'Pemberkatan pukul 09.00 WIB dan Pesta Adat Batak pukul 11.00 WIB.'});const calendar=$('#calendar');calendar.href=`https://calendar.google.com/calendar/render?${cal}`;calendar.target='_blank';calendar.rel='noopener';
  $('#share').onclick=async e=>{try{if(navigator.share)await navigator.share({title:document.title,url:location.href});else{await navigator.clipboard.writeText(location.href);e.currentTarget.textContent='Disalin ✓'}}catch{}};document.querySelectorAll('[data-copy]').forEach(btn=>btn.onclick=async()=>{try{await navigator.clipboard.writeText(btn.dataset.copy);btn.textContent='Berhasil Disalin ✓'}catch{btn.textContent=btn.dataset.copy}});$('#copy-hashtag').onclick=async e=>{try{await navigator.clipboard.writeText(e.currentTarget.dataset.hashtag);e.currentTarget.textContent='Hashtag Disalin ✓'}catch{e.currentTarget.textContent='#NAOWithTheWAN'}};
  $('#rsvp-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget),name=String(d.get('name')).trim(),text=`RSVP Pernikahan Lizwan & Naomi\n\nNama: ${name}\nKehadiran: ${d.get('attendance')}\nJumlah tamu: ${d.get('guests')}\nUcapan: ${String(d.get('message')).trim()}`;$('#status').textContent=`Mauliate, ${name}. WhatsApp akan dibuka.`;window.open(`https://wa.me/6282260327488?text=${encodeURIComponent(text)}`,'_blank','noopener')};
  const dlg=$('#lightbox'),dlgImg=dlg.querySelector('img');document.querySelectorAll('.photo').forEach(btn=>btn.onclick=()=>{const img=btn.querySelector('img');dlgImg.src=img.src;dlgImg.alt=img.alt;dlg.showModal()});dlg.querySelector('button').onclick=()=>dlg.close();dlg.onclick=e=>e.target===dlg&&dlg.close();
});
let youtubePlayer;function onYouTubeIframeAPIReady(){youtubePlayer=new YT.Player('youtube-player',{height:'1',width:'1',videoId:'3fFpkaOjxW8',playerVars:{playsinline:1,controls:0,loop:1,playlist:'3fFpkaOjxW8'},events:{onStateChange:e=>musicState(e.data===YT.PlayerState.PLAYING)}})}function musicState(on){const b=document.getElementById('music');b.classList.toggle('active',on);b.textContent=on?'♫':'♪';b.setAttribute('aria-label',on?'Jeda musik':'Putar musik')}function playMusic(){if(youtubePlayer?.playVideo)youtubePlayer.playVideo()}document.getElementById('music').onclick=()=>{if(!youtubePlayer)return;youtubePlayer.getPlayerState()===YT.PlayerState.PLAYING?youtubePlayer.pauseVideo():youtubePlayer.playVideo()};
